//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Categories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCategory
    {
        public int idUserCategory { get; set; }
        public string CodeCategory { get; set; }
        public string DescCategory { get; set; }
        public Nullable<int> AccessLevel { get; set; }
    }
}
